apiVersion: v1
kind: Service
metadata:
  name: firetracker-api-service
  labels:
    app: firetracker-api
spec:
  selector:
    app: firetracker-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP