apiVersion: v1
kind: Service
metadata:
  name: firetracker-core-service
  labels:
    app: firetracker-core
spec:
  selector:
    app: firetracker-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP