apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firetracker-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: api.firetracker.sivach.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firetracker-api-service
                port:
                  number: 80