name: Publish Service Defaults Package

on:
  push:
    paths:
      - 'FireTracker.ServiceDefaults/**'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore Dependencies
        run: dotnet restore FireTracker.ServiceDefaults/FireTracker.ServiceDefaults.csproj

      - name: Build Project
        run: dotnet build FireTracker.ServiceDefaults/FireTracker.ServiceDefaults.csproj --configuration Release

      - name: Pack NuGet Package
        run: dotnet pack FireTracker.ServiceDefaults/FireTracker.ServiceDefaults.csproj --configuration Release --output ./nuget_packages

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: dotnet nuget push ./nuget_packages/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key $NUGET_API_KEY --skip-duplicate